/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;


import Control.AdmCarrito;
import Control.AdmCliente;
import Control.AdmInventario;
import Control.Admcatalog;
import Control.Exceptions;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import model.Catalogo;
import model.Cliente;



/**
 *
 * @author angeldvvp
 */
public class FrmCompras extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductos
     */
    String nomb,  ape, dir , telf,  email; int edad;
    AdmCliente cl = new AdmCliente ();
    Admcatalog ct;
    AdmCarrito adcpr = new AdmCarrito();int cantidad=1;
      JPanel pan1 ,panft;
      SpinnerModel modelo;
      int IDCLIENTE=0;
    public FrmCompras( int IDCL) {
        initComponents();
        IDCLIENTE =IDCL;
         mostrarCatalogo();
       btactu.setEnabled(false);
        nombusu(IDCLIENTE);
    }

    public FrmCompras() {
     initComponents();
 
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel3 = new javax.swing.JPanel();
        btperfil = new javax.swing.JButton();
        btcersesion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombusu = new javax.swing.JLabel();
        btcarrito = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        scrol = new javax.swing.JScrollPane();
        panelconten = new javax.swing.JPanel();
        panelem = new javax.swing.JPanel();
        btadd = new javax.swing.JButton();
        pnfoto = new javax.swing.JPanel();
        contador = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        btcomprar = new javax.swing.JButton();
        btactu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        setLocation(new java.awt.Point(175, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btperfil.setText("Perfil");
        btperfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        btperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btperfilActionPerformed(evt);
            }
        });

        btcersesion.setText("Cerrar Sesion");
        btcersesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        btcersesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcersesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btcersesion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btperfil)
                    .addComponent(btcersesion))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Compras");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Cliente:");

        txtnombusu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtnombusu.setText("NombreUsu");

        btcarrito.setText("Carrito");
        btcarrito.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        btcarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcarritoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnombusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 788, Short.MAX_VALUE)
                .addComponent(btcarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnombusu)
                    .addComponent(btcarrito))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tuercas, Tornillos y mas"));

        jLabel4.setText("Buscar:");

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orden..." }));

        panelconten.setBackground(new java.awt.Color(255, 255, 204));
        panelconten.setBorder(javax.swing.BorderFactory.createTitledBorder("Catalogo"));
        panelconten.setAutoscrolls(true);

        panelem.setBackground(new java.awt.Color(153, 204, 255));

        btadd.setText("Agregar al carrito");

        pnfoto.setBackground(new java.awt.Color(204, 255, 102));
        pnfoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnfotoLayout = new javax.swing.GroupLayout(pnfoto);
        pnfoto.setLayout(pnfotoLayout);
        pnfotoLayout.setHorizontalGroup(
            pnfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        pnfotoLayout.setVerticalGroup(
            pnfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );

        txtdesc.setColumns(20);
        txtdesc.setRows(5);
        jScrollPane1.setViewportView(txtdesc);

        btcomprar.setText("Comprar");

        javax.swing.GroupLayout panelemLayout = new javax.swing.GroupLayout(panelem);
        panelem.setLayout(panelemLayout);
        panelemLayout.setHorizontalGroup(
            panelemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btadd)
                    .addComponent(btcomprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119))
        );
        panelemLayout.setVerticalGroup(
            panelemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelemLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btadd)
                            .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btcomprar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelcontenLayout = new javax.swing.GroupLayout(panelconten);
        panelconten.setLayout(panelcontenLayout);
        panelcontenLayout.setHorizontalGroup(
            panelcontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelcontenLayout.setVerticalGroup(
            panelcontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcontenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        scrol.setViewportView(panelconten);

        btactu.setText("X");
        btactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btactu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(scrol, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btactu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrol, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 915, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void nombusu(int id){
    
  
    int edad2=0;
    for(Cliente clt : cl.Mostrardatosclientes(id)){
        txtnombusu.setText(clt.getNombres());
        nomb=txtnombusu.getText();
          ape=clt.getApellidos();
         dir=clt.getDireccion();
        telf=clt.getTelefono();
        email=clt.getCorreoElectronico();
         
    
 
Date fecha = new Date();
LocalDate localDate = fecha.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

        Calendar calendar = Calendar.getInstance();
           
        calendar.setTime(clt.getFecha_Nacimineto());
         int añoactual = localDate.getYear();
        // Obtener el año
        int añonacimiento = calendar.get(Calendar.YEAR);
edad2=añonacimiento-añoactual*-1;
edad=edad2;
    }

}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     if(!txtbuscar.getText().equals("")){
      borrarPaneles();
       buscar(txtbuscar.getText());
     }else{
         try {
             throw new Exceptions("Ingrese algun Nombre");
         } catch (Exceptions ex) {
             Logger.getLogger(FrmCompras.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, ex.getMessage());
         }
    }

       
    }//GEN-LAST:event_jButton1ActionPerformed
public void borrarPaneles(){
    for (Component componente :  panelconten.getComponents()) {
    if (componente instanceof JPanel ){
         panelconten.remove(componente);
        panelconten.revalidate(); // Actualiza el contenedor
        panelconten.repaint();
        panelconten.updateUI();
    
    }
}
}
    
public void buscar(String producto){
    try{
    panelconten.remove(pan1);
        panelconten.revalidate(); // Actualiza el contenedor
        panelconten.repaint(); // Repinta el contenedor
    
   
  ct = new  Admcatalog();

 //AdmInventario vt = new AdmInventario();
 //vt.img();
 // vt.imageninv();
     //SE CREAN VARIOS COMPONENTES SEGUN LA CANTIDAD DE OBJETOS EN LA BASE DE DATOS
    
       
        for(Catalogo dt:ct.Buscar(producto)){
          componentes(dt); 
           //pan1.setPreferredSize(new Dimension(450, 5));
           // txtdesc.setPreferredSize(new Dimension(400, 80));
        }
        }catch(Exceptions ex){
     JOptionPane.showMessageDialog(null, ex.getMessage());
        }
}



//LISTENER DEL BOTON AGREGAR RECIBE COMO PARAMETRO UN OBJETO TIPO CATALOGO 
    //DONDE SE ENCUENTRA EL ID DEL MISMO
    class CatalogoActionListener implements ActionListener {
    private Catalogo catalogo;

    public CatalogoActionListener(Catalogo catalogo) {
        this.catalogo = catalogo;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            // try {
            //try {
            // System.out.println(  catalogo.getIdcata());
            //  if(adcpr.VerificarItems(catalogo.getIdcata())!=1){
            // System.out.println(adcpr.VerificarItems(catalogo.getIdcata())+" :valor1");
            adcpr.IngresarItemCarrito(catalogo.getIdcata(),cantidad,IDCLIENTE);
        } catch (Exceptions ex) {
            Logger.getLogger(FrmCompras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
                   JOptionPane.showMessageDialog(null, "Ingresado en el carrito");
               /* } else{
                     System.out.println(adcpr.VerificarItems(catalogo.getIdcata())+" :valor2");
                   // JOptionPane.showMessageDialog(null, "Ya esta ingresado en el carrito");
                }
            } catch (Exceptions ex) {
                Logger.getLogger(FrmCompras.class.getName()).log(Level.SEVERE, null, ex);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmCompras.class.getName()).log(Level.SEVERE, null, ex);
             // JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }*/
    }
}
//LISTENER DEL JSPINNER RECIVE COMO PARAMETRO UN JSPINNER  
    class ContadorListener implements ChangeListener {
  
     private JSpinner cntr;
    
    public ContadorListener(JSpinner spinner) {
        this.cntr = spinner;
    }

        @Override
        public void stateChanged(ChangeEvent e) {
            cantidad=Integer.parseInt(cntr.getValue().toString());
            System.out.println(cantidad);
        }
    }
    
    
    
    
    public void mostrarCatalogo() {
        panelconten.setLayout(new GridLayout(0,2,10,10));
       
        panelconten.remove(panelem);
 
     
  ct = new  Admcatalog();

 //AdmInventario vt = new AdmInventario();
 //vt.img();
 // vt.imageninv();
     //SE CREAN VARIOS COMPONENTES SEGUN LA CANTIDAD DE OBJETOS EN LA BASE DE DATOS
        for(Catalogo dt:ct.Catalogos()){
         componentes(dt);
             
        }  
    }
    
     public void componentes(Catalogo dt){
                pan1= new JPanel();
         panft = new JPanel();
         //lbnbele=new JLabel("xxxxxxxxx");
         JLabel lbft = new JLabel();
          txtdesc = new JTextArea();
          btadd=new JButton("Agregar");
           btcomprar=new JButton("Comprar");
          contador=new JSpinner();
          modelo =  new SpinnerNumberModel(1,  1,   100, 1);
     contador.setModel(modelo);
      btcomprar.setName(dt.getIdcata()+"");
        btadd.setName(dt.getIdcata()+"");//SE LE ASIGNA UN TAG O NOMBRE AL BOTON PARA IDENTIFCAR EL ELEMENTO DEL CATALOGO
        btadd.addActionListener(new CatalogoActionListener(dt));//ENVIA EL OBJETO CATALOGO
      modelo.addChangeListener(new ContadorListener(contador));
      panft.setPreferredSize(new Dimension(100, 100));
       txtdesc.setPreferredSize(new Dimension(400, 80));
        pan1.setPreferredSize(new Dimension(800, 130));
      pan1.setBackground(new Color(153,204,255));
         pnfoto.setBackground(pnfoto.getBackground());
  txtdesc.setText("Nombre: "+dt.getNombre()+"\nMarca:"+dt.getMarca()+"\nDescripcion: "+dt.getDetalles()+
                        "\nPrecio: $"+dt.getPrecio());
              System.out.println("xxx: "+dt.getNombre());
    BufferedImage imagen = dt.img();

    if (imagen != null) {
        // Crea un ImageIcon con la imagen
        ImageIcon icono = new ImageIcon(imagen);

       lbft.setIcon(icono);

    }
    //AGREGAR Y LOS OBJETOS AL PANEL Y ACTUALIZA EL MISMO
panft.add(lbft);
    pan1.add( panft);
     pan1.add( txtdesc);
     pan1.add(contador);
 pan1.add(btadd);    
  pan1.add(btcomprar);   
   panelconten.add(pan1);
  panelconten.updateUI();
 //  System.out.println(panelconten.getSize()+" "+pan1.getWidth());
                   
                
            }
        
 
    
    
    private void btcarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcarritoActionPerformed
       CarritoCompras crp = new CarritoCompras(nomb,  ape,  dir,  telf,  email,  edad);
        crp.setVisible(true);
        
    }//GEN-LAST:event_btcarritoActionPerformed

    private void btactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactuActionPerformed
borrarPaneles();
        mostrarCatalogo();
        btactu.setEnabled(false);
        txtbuscar.setText("");
    }//GEN-LAST:event_btactuActionPerformed

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
      String datos=txtbuscar.getText();
        if(!datos.equals("")){
          btactu.setEnabled(true);
      }else{
          btactu.setEnabled(false);
      }
        
        
        
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void btperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btperfilActionPerformed
        FrmPerfilCL pf = new FrmPerfilCL( nomb,  ape, dir , telf,  email,  edad);
        pf.setVisible(true);
    }//GEN-LAST:event_btperfilActionPerformed

    private void btcersesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcersesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcersesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
                 javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel" );
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btactu;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btcarrito;
    private javax.swing.JButton btcersesion;
    private javax.swing.JButton btcomprar;
    private javax.swing.JButton btperfil;
    private javax.swing.JSpinner contador;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelconten;
    private javax.swing.JPanel panelem;
    private javax.swing.JPanel pnfoto;
    private javax.swing.JScrollPane scrol;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JLabel txtnombusu;
    // End of variables declaration//GEN-END:variables
}
